### ISSUE TITLE
Error when saving the QGIS project

### ISSUE THREAD

**Issue by Malauch** [ccrook/QGIS-MemoryLayerSaver-Plugin#6]
When I try to save project with some memory layer I get Python error message as below:

```
2018-08-04T17:02:22     WARNING    Traceback (most recent call last):
              File "/Users/michaljurewicz/Library/Application Support/QGIS/QGIS3/profiles/Profil2/python/plugins/MemoryLayerSaver/MemoryLayerSaver.py", line 309, in saveData
              with Writer(filename) as writer:
              File "/Users/michaljurewicz/Library/Application Support/QGIS/QGIS3/profiles/Profil2/python/plugins/MemoryLayerSaver/MemoryLayerSaver.py", line 26, in __enter__
              self.open()
              File "/Users/michaljurewicz/Library/Application Support/QGIS/QGIS3/profiles/Profil2/python/plugins/MemoryLayerSaver/MemoryLayerSaver.py", line 34, in open
              print("Filename: {0}".format(self._filename))
             UnicodeEncodeError: 'ascii' codec can't encode character '\u0301' in position 73: ordinal not in range(128)
```

**Comment by Malauch** [comment]
After more tries I have found that the problem is when project name contains any not standard ASCII characters.

**Comment by ccrook** [comment]
@Malauch Thanks for noticing this and for identifying the issue.

**Comment by ccrook** [comment]
@Malauch Should be fixed in version 4.0.2  - the problem was with some debugging code that was still in the plugin.  See if it works for you...

**Comment by rjwillson** [comment]
love this plugin!

any thoughts about the possibility of having the *.mldata file being stored right in the *.qgz file so that everything is contained in the one file?

**Comment by Malauch** [comment]
I can confirm that it's fixed now

**Comment by ccrook** [comment]
@rjwillson Interesting thought Rob - I hadn't considered this but will look at the feasibility of doing so...
